/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "back-g": "var(--back-g)",
        "background-2": "var(--background-2)",
        beige: "var(--beige)",
        blue: "var(--blue)",
        "cta-2": "var(--cta-2)",
        "cta-dark": "var(--cta-dark)",
        "d-9d-9d-9": "var(--d-9d-9d-9)",
        ooro: "var(--ooro)",
        "teal-aqua": "var(--teal-aqua)",
        "text-2": "var(--text-2)",
      },
      fontFamily: {
        "english-body-bold": "var(--english-body-bold-font-family)",
        "english-body-medium": "var(--english-body-medium-font-family)",
        "english-body-rugular": "var(--english-body-rugular-font-family)",
        "english-body-semibold": "var(--english-body-semibold-font-family)",
        "english-display-bold": "var(--english-display-bold-font-family)",
        "english-display-medium": "var(--english-display-medium-font-family)",
        "english-display-regular": "var(--english-display-regular-font-family)",
        "english-display-semibold": "var(--english-display-semibold-font-family)",
        "english-heading-bold": "var(--english-heading-bold-font-family)",
        "english-heading-medium": "var(--english-heading-medium-font-family)",
        "english-heading-regular": "var(--english-heading-regular-font-family)",
        "english-heading-semibold": "var(--english-heading-semibold-font-family)",
        "english-label-bold": "var(--english-label-bold-font-family)",
        "english-label-medium": "var(--english-label-medium-font-family)",
        "english-label-regular": "var(--english-label-regular-font-family)",
        "english-label-semibold": "var(--english-label-semibold-font-family)",
        "english-subtitle-bold": "var(--english-subtitle-bold-font-family)",
        "english-subtitle-medium": "var(--english-subtitle-medium-font-family)",
        "english-subtitle-regular": "var(--english-subtitle-regular-font-family)",
        "english-subtitle-semibold": "var(--english-subtitle-semibold-font-family)",
        "english-title-bold": "var(--english-title-bold-font-family)",
        "english-title-medium": "var(--english-title-medium-font-family)",
        "english-title-regular": "var(--english-title-regular-font-family)",
        "english-title-semibold": "var(--english-title-semibold-font-family)",
        "noto-sans": "var(--noto-sans-font-family)",
        text: "var(--text-font-family)",
      },
      fontSize: {
        'display-large': ['56px', '84px'],
        'body': ['16px', '24px'],
        'body-small': ['12px', '18px'],
      },
      fontWeight: {
        'regular': '400',
        'medium': '500',
        'semibold': '600',
        'bold': '700',
      }
    },
  },
  plugins: [],
};
