#!/bin/bash

# OnPager Test Framework Options Display
# This script shows available test commands and options

echo ""
echo "🎯 OnPager Test Framework - Available Commands"
echo "================================================"
echo ""
echo "🚀 Test Execution Commands:"
echo "  python run_tests.py --unit          # Run unit tests only"
echo "  python run_tests.py --integration   # Run integration tests only"
echo "  python run_tests.py --regression    # Run regression tests only"
echo "  python run_tests.py --robot         # Run Robot Framework tests only"
echo "  python run_tests.py --all           # Run all tests (default)"
echo "  python run_tests.py --parallel      # Enable parallel execution"
echo ""
echo "📊 Information Commands:"
echo "  python run_tests.py --list          # List available test files"
echo "  python run_tests.py --features      # Show feature tracking information"
echo ""
echo "🔧 Direct pytest Commands:"
echo "  python -m pytest tests/unit         # Run unit tests directly"
echo "  python -m pytest tests/integration  # Run integration tests directly"
echo "  python -m pytest tests/regression   # Run regression tests directly"
echo "  python -m pytest -m smoke           # Run smoke tests only"
echo "  python -m pytest -m 'feature(user_authentication)'  # Run specific feature tests"
echo ""
echo "📁 Directory Structure:"
echo "  tests/unit/          # Unit tests"
echo "  tests/integration/   # Integration tests"
echo "  tests/regression/    # Regression tests"
echo "  tests/features/      # Feature-specific tests"
echo "  tests/robot_tests.robot  # Robot Framework tests"
echo "  reports/             # Generated test reports"
echo ""
echo "📋 Quick Examples:"
echo "  # Run all tests with parallel execution"
echo "  python run_tests.py --all --parallel"
echo ""
echo "  # Run specific test type with HTML reports"
echo "  python run_tests.py --unit --html"
echo ""
echo "  # List all available tests"
echo "  python run_tests.py --list"
echo ""
echo "  # Show current feature tracking status"
echo "  python run_tests.py --features"
echo ""
echo "💡 Tips:"
echo "  - Use --parallel for faster test execution"
echo "  - Check reports/ directory for HTML test reports"
echo "  - Feature tracking automatically captures test execution"
echo "  - All tests use pytest markers for easy filtering"
echo ""
echo "================================================"
echo ""

# Also show the actual directory contents
echo "📁 Directory Contents:"
ls -la
